### ISSUE TITLE
Symfony3 compat

### ISSUE THREAD

**Issue by COil** [hautelook/TemplatedUriBundle#17]
Deprecation reported by Symfony 2.8:

`The "scope" attribute of service "hautelook.router.template" in file "/home/workspace/neokf/api/vendor/hautelook/templated-uri-bundle/Hautelook/TemplatedUriBundle/DependencyInjection/../Resources/config/services.xml" is deprecated since version 2.8 and will be removed in 3.0.`

**Comment by COil** [comment]
By the way, can we have a new tag so it can be installed with Symfony3.

**Comment by jsor** [comment]
I'd also appreciate a new tag.

**Comment by stof** [comment]
ping @baldurrensch can you tag the release containing the fix for the Symfony3 compat ?

**Comment by muub** [comment]
@COil @jsor @stof I have pushed a new tag which should allow for Symfony3 compatibility.

**Comment by stof** [comment]
then this issue should probably be closed
