### ISSUE TITLE
New release to fix deprecation from Symfony 4.2

### ISSUE THREAD

**Issue by bdsl** [hautelook/TemplatedUriBundle#28]
Hello,

I see the Symfony 4.2 deprectation of 'A tree builder without a root node' [has already been fixed in the master branch](https://github.com/hautelook/TemplatedUriBundle/commit/869fadda8241f29eff7e3a75289d7679d97ed86c) - it would be great to have this fix as part of a release. I'm currently using this in a 4.2 project and would like to upgrade to Symfony 4.4 or 5 soon.

[This shows the changes in master since the last release](https://github.com/hautelook/TemplatedUriBundle/compare/3.0.0...master) - currently 4 commits.

Thank you

**Comment by goetas** [comment]
solved in https://github.com/hautelook/TemplatedUriBundle/releases/tag/3.1.0

**Comment by bdsl** [comment]
Great, thanks for the quick response @goetas . I don't know if there are any incompatabilities left to mean composer.json shouldn't be amended to declare compatibility with Symfony 5. https://github.com/hautelook/TemplatedUriBundle/blob/690dcd765008e782b21f7f9fd5cadb493e59094a/composer.json#L16

**Comment by bdsl** [comment]
Would you be able to publish the update to Packagist? They don't know about the 3.1.0 release just yet. Looks like if you log once to Packagist they should set up an auto-updating connection to github. https://twitter.com/packagist/status/1037035587453235201?lang=en
