### ISSUE TITLE
Symfony 5 compatibility is broken

### ISSUE THREAD

**Issue by webhdx** [hautelook/TemplatedUriBundle#30]
Looks like with `3.2.0` release you've added SF5 compatibility but you did not tag `hautelook/templated-uri-router` package which is still incompatible with `symfony/routing` 5.0. You can't install this bundle with SF5.

Are you planning to do anything about it or do you need help?

**Comment by goetas** [comment]
is https://github.com/hautelook/TemplatedUriRouter/releases/tag/3.1.0 enough?

**Comment by webhdx** [comment]
Not enough. I've noticed SF5 removes `kernel.name` parameter so `hautelook.router.template` service cannot be initialized. I will provide you with a fix but it will take some time as I need to check with SF 2.8. It will require another release in bundle package.

**Comment by goetas** [comment]
Hmm, ok. Symfony 2.x support can be dropped if that helps

**Comment by webhdx** [comment]
Ideally it would be best to drop Symfony 3.x support as well but I will try to make it work across all versions.

**Comment by webhdx** [comment]
Basically if you drop SF 2.x or 3.x compatibility you'd need to make major release because it will be a BC break for existing installations.

**Comment by goetas** [comment]
Can you please try to make it work with 3. X? If it comes to be too hard, will evaluate other options then

**Comment by webhdx** [comment]
@goetas Can you update packagist? https://packagist.org/packages/hautelook/templated-uri-router is not showing 3.1.0 release.

**Comment by webhdx** [comment]
@goetas I've opened new pull request in bundle & router repositories. It fixes SF5 compatibility and maintains support for older Symfony versions. Are you able to review the code and make new release this week? We are releasing ezsystems/ezplatform 3.0 final next week and we would like to get rid of our temporary fork. Thanks in advance!

**Comment by goetas** [comment]
Solved by https://github.com/hautelook/TemplatedUriBundle/pull/31
