### ISSUE TITLE
Should we check for preg requirements ?

### ISSUE THREAD

**Issue by bdunogier** [hautelook/TemplatedUriBundle#5]
The title says it all. See this commit: https://github.com/bdunogier/TemplatedUriBundle/commit/071c2d856622a72eccfc38dda74e1f68a1af8c36.

Most constraints won't pass since we provide a string as the value while the router expects the value to match a regexp.

Or am I just doing it wrong ?

**Comment by stof** [comment]
See https://github.com/hautelook/TemplatedUriRouter/pull/14 for the fix (with a test proving it is necessary)

**Comment by stof** [comment]
this can be closed now that we have the fix in the library

**Comment by adrienbrault** [comment]
Available in [2.0.1](https://github.com/hautelook/TemplatedUriRouter/releases/tag/2.0.1)
